# .github/workflows/docker-build.yml
# This workflow automates building and pushing your Docker image for starktech

name: Build and Push Starktech Image

on:
  push:
    branches: [ "main" ] # Trigger this workflow when code is pushed to the 'main' branch
  pull_request:
    branches: [ "main" ] # Optionally, also run on pull requests to 'main'

jobs:
  build_and_push:
    runs-on: ubuntu-latest # The virtual machine environment where the job will run

    steps:
    - name: Checkout code
      uses: actions/checkout@v4 # Action to get your repository's code

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3 # Recommended for modern, efficient Docker builds

    - name: Log in to Docker Registry
      uses: docker/login-action@v3
      with:
        # ***********************************************************************************
        # *** CRITICAL: YOU MUST CUSTOMIZE THIS SECTION FOR YOUR DOCKER REGISTRY! ***
        # Choose ONLY ONE option below (Docker Hub OR GitHub Container Registry)

        # OPTION 1: For Docker Hub
        # Make sure you have created DOCKER_USERNAME and DOCKER_TOKEN secrets in your GitHub repo settings.
        # Your Docker username is 922125.
        username: ${{ secrets.922125 }} # Value should be 922125
        password: ${{ secrets.dckr_pat_QX1ee6wNpoztVF2sW1SoD6CyoUo }}    # You MUST create this secret with your Docker Hub Access Token
        #
        # OPTION 2: For GitHub Container Registry (GHCR - ghcr.io)
        # Make sure you have created GHCR_TOKEN secret (GitHub PAT with 'write:packages' scope) in your GitHub repo settings.
        # username: ${{ github.repository_owner }} # This uses your GitHub username automatically for GHCR
        # password: ${{ secrets.GHCR_TOKEN }}
        # registry: ghcr.io # Uncomment this line to explicitly specify GHCR
        # ***********************************************************************************

    - name: Build and push Starktech Docker image
      uses: docker/build-push-action@v5
      with:
        # Context: The directory containing your Dockerfile and the code it needs.
        # We assume the Dockerfile is at the root of starktech:
        context: ./
        # File: The path to the Dockerfile.
        # We assume it's named 'Dockerfile' and is at the root:
        file: ./Dockerfile

        push: true # Set to 'true' to push the image to the registry

        # ***********************************************************************************
        # *** IMAGE TAGS - FILLED IN WITH YOUR USERNAME ***
        # Your Docker username is 922125.
        # Replace 'starktech-frontend' with your desired name for this Docker image (e.g., 'starktech-web').
        tags: |
          922125/starktech-frontend:latest
          922125/starktech-frontend:${{ github.sha }} # Tags with the specific Git commit hash
          922125/starktech-frontend:${{ github.ref_name }} # Tags with the branch name (e.g., 'main')
        # ***********************************************************************************
